# Generated by Django 5.2 on 2025-05-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=250, unique=True)),
                ('Description', models.CharField(max_length=250)),
                ('Bv', models.IntegerField()),
                ('Dollard', models.IntegerField()),
                ('prix_distributeur', models.IntegerField()),
                ('Prix_en_detail', models.IntegerField()),
            ],
        ),
    ]
