# Generated by Django 5.2 on 2025-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='Description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
