# Generated by Django 5.2.1 on 2025-06-15 08:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=250, unique=True)),
                ('Description', models.CharField(max_length=250, null=True)),
                ('Bv', models.IntegerField()),
                ('Dollard', models.IntegerField()),
                ('Prix_distributeur', models.IntegerField()),
                ('Prix_en_detail', models.IntegerField()),
                ('Nombre', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='uploads/')),
                ('mobile', models.CharField(max_length=50)),
                ('poste', models.CharField(default='', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2025, 6, 15, 8, 18, 53, 980236, tzinfo=datetime.timezone.utc))),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=50, unique=True)),
                ('member_name', models.CharField(max_length=250, unique=True)),
                ('depth', models.CharField(max_length=50)),
                ('directline', models.CharField(max_length=50)),
                ('sponsor', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(max_length=50)),
                ('gbv', models.CharField(max_length=50)),
                ('cpbv', models.CharField(max_length=50)),
                ('cnbv', models.CharField(max_length=50)),
                ('pbv', models.CharField(max_length=50)),
                ('tnbv', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rendevous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(default=0, max_length=50)),
                ('quantite', models.IntegerField()),
                ('prixtotale', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epharma.profile')),
            ],
        ),
    ]
