# Generated by Django 5.2.1 on 2025-05-29 08:46

import datetime
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=250, unique=True)),
                ('Description', models.CharField(max_length=250, null=True)),
                ('Bv', models.IntegerField()),
                ('Dollard', models.IntegerField()),
                ('prix_distributeur', models.IntegerField()),
                ('Prix_en_detail', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2025, 5, 29, 8, 46, 5, 747881, tzinfo=datetime.timezone.utc))),
                ('member_code', models.CharField(max_length=50, unique=True)),
                ('mamber_name', models.CharField(max_length=250, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('directline', models.CharField(max_length=50)),
                ('sponsor', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(max_length=50)),
                ('gbv', models.CharField(max_length=50)),
                ('cpbv', models.CharField(max_length=50)),
                ('cnbv', models.CharField(max_length=50)),
                ('pbv', models.CharField(max_length=50)),
                ('tnbv', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('odjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prixtotale', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epharma.produits')),
            ],
        ),
    ]
