# Generated by Django 5.2.1 on 2025-05-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0002_remove_user_is_admin_remove_user_prenom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
