# Generated by Django 5.2.1 on 2025-06-16 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0002_alter_rendevous_user_alter_user_date_joined_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 7, 36, 30, 812409, tzinfo=datetime.timezone.utc)),
        ),
    ]
