# Generated by Django 5.2.1 on 2025-05-29 14:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0002_alter_user_date_joined_alter_user_depth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adresse',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cnbv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpbv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='directline',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gbv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mamber_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='member_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pbv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tnbv',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 14, 47, 49, 212973, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=50, unique=True)),
                ('member_name', models.CharField(max_length=250, unique=True)),
                ('depth', models.CharField(max_length=50)),
                ('directline', models.CharField(max_length=50)),
                ('sponsor', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(max_length=50)),
                ('gbv', models.CharField(max_length=50)),
                ('cpbv', models.CharField(max_length=50)),
                ('cnbv', models.CharField(max_length=50)),
                ('pbv', models.CharField(max_length=50)),
                ('tnbv', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
