# Generated by Django 5.2.1 on 2025-06-17 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cnbv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpbv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='directline',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gbv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pbv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sponsor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tnbv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 9, 32, 25, 12299, tzinfo=datetime.timezone.utc)),
        ),
    ]
