# Generated by Django 5.2.1 on 2025-05-31 12:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0003_alter_user_managers_rename_adresse_user_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 12, 13, 23, 882256, tzinfo=datetime.timezone.utc)),
        ),
    ]
