# Generated by Django 5.2.1 on 2025-06-03 22:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0004_alter_profile_user_alter_user_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='prix_distributeur',
            new_name='Prix_distributeur',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 22, 54, 33, 204291, tzinfo=datetime.timezone.utc)),
        ),
    ]
