# Generated by Django 5.2.1 on 2025-07-03 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0005_alter_user_date_joined_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 3, 9, 37, 16, 940759, tzinfo=datetime.timezone.utc)),
        ),
    ]
