# Generated by Django 5.2.1 on 2025-06-07 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0006_alter_user_date_joined_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 16, 48, 8, 609098, tzinfo=datetime.timezone.utc)),
        ),
    ]
