# Generated by Django 5.2.1 on 2025-07-03 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0006_user_confirmed_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendevous',
            name='heure',
            field=models.TimeField(default=datetime.time(6, 0), unique=True),
        ),
        migrations.AlterField(
            model_name='rendevous',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 3, 23, 13, 7, 413471, tzinfo=datetime.timezone.utc)),
        ),
    ]
