# Generated by Django 5.2.1 on 2025-06-07 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0011_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 17, 27, 18, 623887, tzinfo=datetime.timezone.utc)),
        ),
    ]
