# Generated by Django 5.2.1 on 2025-06-07 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0012_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 18, 2, 0, 20481, tzinfo=datetime.timezone.utc)),
        ),
    ]
