# Generated by Django 5.2.1 on 2025-06-11 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0013_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 18, 8, 10, 646747, tzinfo=datetime.timezone.utc)),
        ),
    ]
