# Generated by Django 5.2.1 on 2025-06-11 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0014_user_poste_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 21, 18, 4, 355440, tzinfo=datetime.timezone.utc)),
        ),
    ]
