# Generated by Django 5.2.1 on 2025-06-14 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0016_alter_user_date_joined_rendevous'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='Nombre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 12, 17, 29, 210419, tzinfo=datetime.timezone.utc)),
        ),
    ]
