# Generated by Django 5.2.1 on 2025-06-14 13:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0017_produits_nombre_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 13, 8, 29, 658056, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epharma.produits'),
        ),
    ]
