# Generated by Django 5.2.1 on 2025-06-14 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epharma', '0018_alter_user_date_joined_alter_vente_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 13, 13, 12, 949344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vente',
            name='produit',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
